name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fill in secrets
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
        echo ${MAPBOX_DOWNLOADS_TOKEN} > ~/.gradle/gradle.properties
        pwd
        ls
        echo ${MAPBOX_ACCESS_TOKEN} >> ./app/src/main/res/values/secrets.xml
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
